### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [MohamedBassem/gormgen#1]
First of all, thanks for creating and sharing a nice software!

Could you add LICENSE file?
The following page may help for choosing a license.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache License 2.0.
Thanks!

**Comment by MohamedBassem** [comment]
Thanks! Done adding the MIT License : 0a2d9ce6a43a2e90dd4005bb271a291de27a6550

**Comment by hnakamur** [comment]
Thanks!
